### ISSUE TITLE
Update Australian Dollar to AUD or AU$

### ISSUE THREAD

**Issue by Chrisbrozek** [bigcartel/bigcartel-currency-locales#3]
Australian customers who set their currency to AUD just get the generic dollar sign. It would be great if it was specific to their currency so that it either said AUD or AU$ before the price.

**Comment by brettchalupa** [comment]
Closing this as it has been moved to Pivotal Tracker to be prioritized accordingly: https://www.pivotaltracker.com/story/show/155044253
